version: '3'

services:
  router:
    build: ./nginx
    container_name: router
    ports:
      - "80:80"
    environment: 
      NGINX_PORT: 80
    links:
      - backend
      - search
      - actions
  backend:
    build: ./backend
    container_name: backend
    command: node server
    ports:
      - "8080:8080"
    environment: 
      NODE_ENV: development
      PORT: 8080
  search:
    build: ./search
    container_name: search
    command: node server
    ports: 
      - "8081:8081"
    environment:
      NODE_ENV: development
      PORT: 8081
  actions:
    build: ./actions
    container_name: actions
    command: node server
    ports:
      - "8082:8082"
    environment:
      NODE_ENV: development
      PORT: 8082