version: '3'

services:
  router:
    build: ./nginx
    container_name: router
    ports:
      - 80:80
    environment: 
      NGINX_PORT: 80
    links:
      - backend
      - search
      - actions
  backend:
    build: ./backend
    container_name: backend
    command: node server
    ports:
      - 8080:8080
    environment: 
      NODE_ENV: development
      PORT: 8080
    links:
      - mssql
  search:
    build: ./search
    container_name: search
    command: node server
    ports: 
      - 8081:8081
    environment:
      NODE_ENV: development
      PORT: 8081
    links:
      - elasticsearch
      - mssql
  actions:
    build: ./actions
    container_name: actions
    command: node server
    ports:
      - 8082:8082
    environment:
      NODE_ENV: development
      PORT: 8082
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: kibana
    ports: 
      - 5601:5601
    links:
      - elasticsearch
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - ./mssql/data:/var/opt/mssql
      - ./mssql:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./start.sh; ./start.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: Remoting1041!